// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "OrderBeverageService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::vending_machine;

class OrderBeverageServiceHandler : virtual public OrderBeverageServiceIf {
 public:
  OrderBeverageServiceHandler() {
    // Your initialization goes here
  }

  void PlaceOrder(std::string& _return, const int64_t city) {
    // Your implementation goes here
    printf("PlaceOrder\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<OrderBeverageServiceHandler> handler(new OrderBeverageServiceHandler());
  shared_ptr<TProcessor> processor(new OrderBeverageServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

